### ISSUE TITLE
other modules

### ISSUE THREAD

**Issue by Bees-MD** [Marty1820/picow-epaper-2.9-B#1]
have you tried using picodisplay and adafruit_framebuf? just messing around not sure if its compatible 

```
from machine import Pin, SPI
import picodisplay as display
from adafruit_framebuf import FrameBuffer

#numbers might be wrong adjust as ness
spi = SPI(0)  # SPI bus 0
cs = Pin(17, Pin.OUT)  # Chip Select
sck = Pin(18, Pin.OUT)  # Serial Clock
mosi = Pin(19, Pin.OUT)  # Master Out Slave In
miso = Pin(16, Pin.IN)  # Master In Slave Out
dc = Pin(20, Pin.OUT)   # Data/Command
reset = Pin(21, Pin.OUT)  # Reset
busy = Pin(22, Pin.IN)  # Busy

#create and initialize a display
disp = display.Display(spi, cs, sck, mosi, miso, dc, reset, busy)
disp.init()

# Set a font
font = "font.ttf"  # You need to provide your own font file
size = 16

# Create a frame buffer
buf = FrameBuffer(disp.width, disp.height, display.EPD_WHITE)

# Write text to the buffer
buf.text((0, 0), "Hello, World!", font, size, display.EPD_BLACK)

# Display the frame buffer on the ePaper screen
disp.display(buf.buffer())
```

request from the chatbot "If possible, consider using an ESP32 or similar microcontroller with native support for SPI and GPIO pins for better compatibility with ePaper displays."

**Comment by Marty1820** [comment]
I can't find any documentation for `picodisplay` other than a mention about it being used for LCD displays. For FrameBuffer on a pico, from what I can tell, it's version of MicroPython is done with `import framebuf` and not using the `adafruit_framebuf` module.

I'm also using what I own which is a Raspberry Pi PicoW and a Waveshare Pico-ePaper-2.9_B v3. I'm not going to purchase other hardware just to make things easier.
